name: publish

on:
  push:
    branches: [main] # master 分支有 push 时触发
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - .github/workflows/*

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm

    steps:
      # 下载源码
      # 这一步就是检出你的仓库并下载里面的代码到runner中,actions/checkout@v2是官方自己造的轮子，直接拿来用就行
      - name: Checkout
        uses: actions/checkout@v2

      # 打包构建
      - name: Install and Build
        run: |
          yarn
          yarn build

      # 更新版本号并发布到NPM
      - name: Publish to NPM
        run: |
          git config --global user.name $USER_NAME
          git config --global user.email $USER_EMAIL
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm version patch
          npm publish

        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          USER_NAME: ${{ secrets.MY_USER_NAME }}
          USER_EMAIL: ${{ secrets.MY_USER_EMAIL }}
