name: publish

on:
  push:
    branches: [main] # master 分支有 push 时触发
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm

    steps:
      # 下载源码
      # 这一步就是检出你的仓库并下载里面的代码到runner中,actions/checkout@v2是官方自己造的轮子，直接拿来用就行
      - name: Checkout
        uses: actions/checkout@v2

      # 打包构建
      - name: Install and Build
      - run: npm install # 安装依赖
      - run: npm version patch # 更新版本号
      - run: npm run build # 打包

      # 部署到 GitHub pages
      - name: Publish to the npm registry
        uses: primer/publish@3.0.0

        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致

        with:
          default_branch: 'master'
