name: publish

on:
  push:
    branches: [main] # master 分支有 push 时触发
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 下载源码
      # 这一步就是检出你的仓库并下载里面的代码到runner中,actions/checkout@v2是官方自己造的轮子，直接拿来用就行
      - name: Checkout
        uses: actions/checkout@v2

      # 打包构建
      - name: Build
        uses: actions/setup-node@master
        with:
          node-version: '14.x'
      - run: yarn install # 安装依赖
      - run: yarn build # 打包

      # 部署到 GitHub pages
      - name: Publish
        uses: actions/setup-node@master
        with:
          node-version: '14.x'
      - run: npm version patch # 更改小版本号
      - run: npm publish # 发布

